controller_manager:
  ros__parameters:
    update_rate: 100

    gpio_controller:
      type: gpio_controllers/GPIOController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

gpio_controller:
  ros__parameters:
    command_interfaces:
      - value
    state_interfaces:
      - value
    joints:
      - button
