#ifndef WAREHOUSE_MAP_HPP
#define WAREHOUSE_MAP_HPP

#include <string>
#include <unordered_map>

extern const float AISLE_MIN_HEIGHT_CONT;
extern const float AISLE_MAX_HEIGHT_CONT;

/*
aisle number and disc y are for waypoint ordering
cont x and cont y are the locations of the waypoint in the map generated by slam
*/

struct Item {
    int index;
    int aisle;    // waypoint ordering
    float disc_y;
    float cont_x;
    float cont_y;
    int shelf_height;
    bool side_of_aisle;
};

extern std::unordered_map<std::string, Item> store_map;
extern std::unordered_map<int, std::string> index_to_item_name_map;

#endif
